/*
 * Ultrasonic.h
 *
 *  Created on: Oct 11, 2024
 *      Author: SoO
 *
 * Module: Ultrasonic sensor
 *
 * File Name: Ultrasonic.h
 *
 * Description: header file for the ultrasonic sensor driver
 */

#ifndef ULTRASONIC_H_
#define ULTRASONIC_H_
#include"std_types.h"


/*******************************************************************************
 *                                Definitions                                  *
 *******************************************************************************/
#define TRIGGER_PORT   PORTD_ID
#define TRIGGER_PIN    PIN7_ID

/*******************************************************************************
 *                      Functions Prototypes                                   *
 *******************************************************************************/

/*
 * Description :
 * Function responsible for initializing the ultrasonic sensor.
 */
void Ultrasonic_init(void);

/*
 * Description :
 * Function responsible for sending the trigger pulse to the ultrasonic sensor.
 */
void Ultrasonic_Trigger(void);

/*
 * Description :
 * Function responsible for:
 * 1.sending the trigger pulse by using the Ultrasonic_Trigger function.
 * 2.start the measurement process via the ICU driver.
 */
uint16 Ultrasonic_readDistance(void);

/*
 * Description :
 * Function responsible for:
 * 1.the callback function called by the ICU driver.
 * 2.it calculates the high time (pulse time) generated by the ultrasonic sensor.
 */
void Ultrasonic_edge_processing(void);

#endif /* ULTRASONIC_H_ */
